version: 2

models:
    - name: base_eligibility
      config:
        database: "{{ var('output_database') }}"
        schema: "{{ var('output_schema') }}"
        materialized: ephemeral
      description: >
        Base model for eligibility source data. Includes logic to create a 
        blank table if the source is missing and adds a row_hash column.
