version: 2

models:
    - name: eligibility_detail
      config:
        database: "{{ var('output_database') }}"
        schema: "{{ var('output_schema') }}"
        materialized: table
      description: >
        Data profiling on eligibility source data with columns for source 
        primary keys and every data quality check performed.
      tests:
        - unique:
            column_name: "(patient_id||'-'||month||'-'||year)"

      columns:
        - name: patient_id
          description: Primary key for grain - value from source file

        - name: month
          description: Primary key for grain - value from source file

        - name: year
          description: Primary key for grain - value from source file

        - name: duplicate_record_elig
          description: >
            Boolean value if the entire record is a duplicate, 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: duplicate_patient_id_elig
          description: >
            Boolean value if not a unique combination of patient_id, month,
            year, and payer, 0 (pass) or 1 (fail). Join to test_catalog on 
            test_name for more details.

        - name: missing_patient_id_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: missing_month_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: missing_year_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: missing_gender_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: missing_birth_date_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: missing_deceased_date_elig
          description: >
            Boolean value if missing (null) or blank (''), 0 (pass) 
            or 1 (fail). Join to test_catalog on test_name for more details.

        - name: invalid_birth_date_elig
          description: >
            Boolean value if invalid or future date, 0 (pass) or 1 (fail) 
            or null (not applicable). Join to test_catalog on test_name for 
            more details.

        - name: invalid_deceased_date_elig
          description: >
            Boolean value if invalid or future date, 0 (pass) or 1 (fail) 
            or null (not applicable). Join to test_catalog on test_name for 
            more details.

        - name: invalid_death_before_birth_elig
          description: >
            Time sequence test: boolean value if death date is before birth 
            date, 0 (pass) or 1 (fail) or null (not applicable). Join to 
            test_catalog on test_name for more details.

        - name: invalid_gender_elig
          description: >
            Valid values test: boolean value if invalid value, 0 (pass) or 
            1 (fail) or null (not applicable). Join to test_catalog on test_name 
            for more details.

        - name: run_date
          description: Datetime the model was run used for snapshots
