version: 2

models:
    - name: eligibility_detail
      config:
        database: "{{ var('output_database') }}"
        schema: "{{ var('output_schema') }}"
        materialized: table
      description: >
        Data profiling on eligibility source data with columns for source 
        primary keys and every data quality check performed.
      tests:
        - unique:
            column_name: "(patient_id||'-'||month||'-'||year||'-'||payer||'-'||payer_type)"

      columns:
        - name: patient_id
          description: Primary key for grain - value from source file

        - name: month
          description: Primary key for grain - value from source file

        - name: year
          description: Primary key for grain - value from source file

        - name: duplicate_record_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: duplicate_patient_id_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_patient_id_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_month_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_year_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_gender_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_birth_date_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_deceased_date_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_birth_date_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_deceased_date_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_death_before_birth_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_gender_elig
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: run_date
          description: Datetime the model was run used for snapshots
