version: 2

models:
    - name: medical_claim_detail
      config:
        database: "{{ var('output_database') }}"
        schema: "{{ var('output_schema') }}"
        materialized: table
      description: >
        Data profiling on medical claim line source data with columns for 
        source primary keys and every data quality check performed.
      tests:
        - unique:
            column_name: "(claim_id||'-'||claim_line_number)"

      columns:
        - name: claim_id
          description: Primary key for grain - value from source file

        - name: claim_line_number
          description: Primary key for grain - value from source file

        - name: duplicate_record_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: duplicate_claim_id_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_fk_patient_id_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_claim_id_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_claim_line_number_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_patient_id_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_claim_start_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_claim_end_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_admission_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_discharge_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_claim_type_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_bill_type_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_place_of_service_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_revenue_center_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_hcpcs_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_billing_npi_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_rendering_npi_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_facility_npi_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_paid_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_paid_amount_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_diagnosis_code_1_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: missing_diagnosis_poa_1_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_claim_start_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_claim_end_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_admission_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_discharge_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_paid_date_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_claim_end_before_start_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_discharge_before_admission_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_claim_type_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_bill_type_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_place_of_service_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_discharge_disposition_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_ms_drg_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_revenue_center_code_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_diagnosis_code_1_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: invalid_diagnosis_poa_1_med
          description: >
            See test_catalog seed table and join on test_name 
            for more details.

        - name: run_date
          description: Datetime the model was run used for snapshots
